const TOTAL=450,PRICE=10,$=id=>document.getElementById(id);
const playerId=localStorage.getItem("zhaanBingoPlayerId")||crypto.randomUUID();
localStorage.setItem("zhaanBingoPlayerId",playerId);
const socket=io({auth:{playerId}});
let selected=[],sold=new Set(),called=[],current=null,cards=new Map(),previews=new Map(),marked=new Set();
const fmt=n=>`${["B","I","N","G","O"][Math.floor((n-1)/15)]}-${n}`;
function card(t,mini=false){return `<div class="preview ${mini?"mini":""}"><div class="title"><span>#${t.id}</span><span>B I N G O</span></div><div class="bingo head"><b>B</b><b>I</b><b>N</b><b>G</b><b>O</b></div><div class="card">${t.numbers.map((n,i)=>`<button class="cell ${n==="FREE"?"free":""} ${n==="FREE"||marked.has(`${t.id}-${i}`)?"marked":""}" data-ticket="${t.id}" data-cell="${i}">${n==="FREE"?"★":n}</button>`).join("")}</div></div>`}
function renderTickets(){let h="";for(let i=1;i<=TOTAL;i++){let unavailable=sold.has(i)&&!selected.includes(i);h+=`<button class="ticket ${selected.includes(i)?"selected":""} ${unavailable?"sold":""}" ${unavailable?"disabled":""} data-id="${i}">${i}</button>`}$("tickets").innerHTML=h;$("soldCount").textContent=sold.size}
function renderSlots(){$("slots").innerHTML=[0,1].map(i=>{let id=selected[i],t=previews.get(id);return id&&t?`<div class="slot chosen"><button class="remove-ticket" data-remove="${id}" aria-label="Remove ticket">×</button>${card(t,true)}</div>`:`<div class="slot empty-slot"><strong>＋</strong><small>SLOT ${i+1} EMPTY</small></div>`}).join("");$("bal").textContent=(1000-selected.length*PRICE).toFixed(2)}
function requestPreviews(){socket.emit("preview_tickets",{tickets:selected})}
function board(){const numbers=Array.from({length:15},(_,row)=>[row+1,row+16,row+31,row+46,row+61]).flat();$("board").innerHTML=numbers.map(n=>`<div class="${called.includes(n)?"called":""} ${n===current?"latest":""}">${n}</div>`).join("")}
function playerCards(){const visibleCards=cards.size?cards:previews;$("cards").innerHTML=visibleCards.size?[...visibleCards.values()].map(t=>`<article class="pcard">${card(t)}<footer>BINGO! <small>#${t.id}</small></footer></article>`).join(""):`<div class="card-loading">Your ticket is loading…</div>`}
function hasBingo(ticket){const hit=i=>ticket.numbers[i]==="FREE"||marked.has(`${ticket.id}-${i}`);const row=[0,1,2,3,4].some(r=>[0,1,2,3,4].every(c=>hit(r*5+c)));const column=[0,1,2,3,4].some(c=>[0,1,2,3,4].every(r=>hit(r*5+c)));return row||column||[0,4,20,24].every(hit)}
function apply(s){sold=new Set(s.sold||[]);called=s.called||[];current=s.current?.number||null;$("timer").textContent=s.phase==="buying"?`${s.timeLeft}s`:"LIVE";$("count").textContent=`${called.length}/75`;$("status").textContent=s.phase==="playing"?"LIVE":s.phase.toUpperCase();if(s.phase==="buying"){$("buy").classList.remove("hidden");$("game").classList.add("hidden");renderTickets();renderSlots()}else{$("buy").classList.add("hidden");$("game").classList.remove("hidden");board();playerCards();$("recent").innerHTML=called.slice(-3).reverse().map(n=>`<span>${fmt(n)}</span>`).join("")}if(s.current){$("ball").textContent=s.current.display;$("ball").className="ball green"}}
function saveSelection(){requestPreviews();if(selected.length)socket.emit("reserve_tickets",{tickets:selected});else socket.emit("release_tickets");renderTickets();renderSlots()}
$("tickets").onclick=e=>{let id=Number(e.target.dataset.id);if(!id)return;if(selected.includes(id))selected=selected.filter(n=>n!==id);else if(selected.length<2)selected.push(id);else return alert("Maximum 2 tickets.");saveSelection()};
$("slots").onclick=e=>{let id=Number(e.target.dataset.remove);if(!id)return;selected=selected.filter(n=>n!==id);saveSelection()};
$("theme").onclick=()=>{document.body.classList.toggle("dark");$("theme").textContent=document.body.classList.contains("dark")?"☀️ Light":"🌙 Dark"};
$("cards").onclick=e=>{let c=e.target.closest(".cell"),id=Number(c?.dataset.ticket),i=Number(c?.dataset.cell),t=cards.get(id);if(!t)return;let n=t.numbers[i];if(n!=="FREE"&&!called.includes(n))return;for(const ticket of cards.values())ticket.numbers.forEach((value,index)=>{if(value===n)marked.add(`${ticket.id}-${index}`)});playerCards();for(const ticket of cards.values())if(hasBingo(ticket))socket.emit("claim_bingo",{ticketId:ticket.id})};
socket.on("state",apply);socket.on("ticket_previews",ts=>{previews=new Map(ts.map(t=>[t.id,t]));cards=new Map(previews);renderSlots();playerCards()});socket.on("tickets_reserved",d=>{selected=d.tickets;requestPreviews();renderTickets();renderSlots()});socket.on("ticket_cards",ts=>{cards=new Map(ts.map(t=>[t.id,t]));playerCards()});socket.on("ball_called",b=>{current=b.number;if(!called.includes(b.number))called.push(b.number);board();playerCards();$("ball").textContent=b.display;$("ball").className="ball green";$("msg").textContent="NEW BALL — mark it on your ticket"});socket.on("bingo_claimed",w=>{const mine=selected.includes(w.ticketId);$("win").textContent=mine?`🎉 YOU WIN! Ticket #${w.ticketId} — ${w.pattern}`:`🎉 BINGO! Ticket #${w.ticketId} — ${w.pattern}`;$("win").classList.remove("hidden")});socket.on("ticket_error",m=>alert(m));socket.on("game_finished",()=>{$("status").textContent="FINISHED";$("msg").textContent="Game finished"});
renderTickets();renderSlots();
